set_property PACKAGE_PIN M15 [get_ports ovflo_full_n]
set_property PACKAGE_PIN V14 [get_ports ovflo_din]
set_property PACKAGE_PIN V19 [get_ports ovflo_write]
set_property IOSTANDARD LVCMOS33 [get_ports ovflo_din]
set_property IOSTANDARD LVCMOS33 [get_ports ovflo_full_n]
set_property IOSTANDARD LVCMOS33 [get_ports ovflo_write]
